"""add due_date to task

Revision ID: 30534bc46248
Revises: 63ab82dd53d2
Create Date: 2026-07-23 21:41:39.315002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30534bc46248'
down_revision: Union[str, None] = '63ab82dd53d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_table', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_table', 'due_date')
    # ### end Alembic commands ###
