"""add priority column to task table

Revision ID: 63ab82dd53d2
Revises: 9eec22416e67
Create Date: 2026-07-23 14:57:58.679131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ab82dd53d2'
down_revision: Union[str, None] = '9eec22416e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'task_table',
    sa.Column(
        'priority',
        sa.String(),
        nullable=False,
        server_default='medium'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_table', 'priority')
    # ### end Alembic commands ###
